services:
  callback:
    container_name: callback
    build:
      context: ./callback
      target: prod
    volumes:
      - "media:/yt-media"
      - "./callback/app:/app"
    ports:
      - "5000:5000"
      - "80:80"

volumes:
  media: