services:
  callback:
    container_name: callback
    build:
      context: ./callback
      target: callback-yt-prod
    environment:
      - "AUDIO_YOUTUBE_TOKEN=none specified"
    volumes:
      - "media:/yt-media"
    ports:
      - "80:80"
    stop_signal: SIGINT

volumes:
  media: